//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhillyZoo_App.DestinationLayer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class DestinationObjectLayer
    {
        public DestinationObjectLayer()
        {
            this.DestinationEnterExists = new HashSet<DestinationEnterExists>();
            this.DestinationMenu = new HashSet<DestinationMenu>();
            this.DestinationPhotos = new HashSet<DestinationPhotos>();
        }
    
        public int id { get; set; }
        public int mapPointId { get; set; }
        public int statusTypeId { get; set; }
        public string destinationName { get; set; }
        public string shortDescription { get; set; }
        public string longDescription { get; set; }
        public System.DateTime openingTime { get; set; }
        public System.DateTime closingTime { get; set; }
    
        public virtual ICollection<DestinationEnterExists> DestinationEnterExists { get; set; }
        public virtual ICollection<DestinationMenu> DestinationMenu { get; set; }
        public virtual MapPoint MapPoint { get; set; }
        public virtual MapPointStatusType MapPointStatusType { get; set; }
        public virtual ICollection<DestinationPhotos> DestinationPhotos { get; set; }
    }
}
