//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhillyZoo_App.DestinationLayer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Itinerary
    {
        public int mapPointId { get; set; }
        public int userId { get; set; }
        public Nullable<int> sortOrder { get; set; }
    
        public virtual MapPoint MapPoint { get; set; }
    }
}
