//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhillyZoo_App.DestinationLayer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class MapPointEdges
    {
        public int mapPointEdgestId { get; set; }
        public int mapPointIdA { get; set; }
        public int mapPointIdB { get; set; }
        public decimal distance { get; set; }
    
        public virtual MapPoint MapPoint { get; set; }
        public virtual MapPoint MapPoint1 { get; set; }
    }
}
