//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhillyZoo_App.DestinationLayer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class MapPoint
    {
        public MapPoint()
        {
            this.MapPointEdges = new HashSet<MapPointEdges>();
            this.MapPointEdges1 = new HashSet<MapPointEdges>();
            this.DestinationObjectLayer = new HashSet<DestinationObjectLayer>();
            this.Itinerary = new HashSet<Itinerary>();
        }
    
        public int mapPointId { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public decimal latitude { get; set; }
        public decimal longitude { get; set; }
        public Nullable<int> imageX { get; set; }
        public Nullable<int> imageY { get; set; }
        public int mapPointTypeId { get; set; }
    
        public virtual MapPointType MapPointType { get; set; }
        public virtual ICollection<MapPointEdges> MapPointEdges { get; set; }
        public virtual ICollection<MapPointEdges> MapPointEdges1 { get; set; }
        public virtual ICollection<DestinationObjectLayer> DestinationObjectLayer { get; set; }
        public virtual ICollection<Itinerary> Itinerary { get; set; }
    }
}
