//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhillyZoo_App.DestinationLayer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class PushType
    {
        public PushType()
        {
            this.User_PushType = new HashSet<User_PushType>();
        }
    
        public int pushTypeId { get; set; }
        public string type { get; set; }
    
        public virtual ICollection<User_PushType> User_PushType { get; set; }
    }
}
