//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhillyZoo_App.DestinationLayer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.JWTToken = new HashSet<JWTToken>();
            this.PushMessage = new HashSet<PushMessage>();
            this.Sessions = new HashSet<Sessions>();
            this.User_PushType = new HashSet<User_PushType>();
            this.Itinerary = new HashSet<Itinerary>();
        }
    
        public int userID { get; set; }
        public Nullable<System.DateTime> last_accessed { get; set; }
        public bool enabled { get; set; }
        public string membershipId { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public System.DateTime createdTS { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual ICollection<JWTToken> JWTToken { get; set; }
        public virtual ICollection<PushMessage> PushMessage { get; set; }
        public virtual ICollection<Sessions> Sessions { get; set; }
        public virtual ICollection<User_PushType> User_PushType { get; set; }
        public virtual ICollection<Itinerary> Itinerary { get; set; }
    }
}
